### ISSUE TITLE
Unable to create an account

### ISSUE THREAD

**Issue by sabrinaweb** [Mr17MG/Memorito#1]
Dear developers,
I have tried to create an account to use your app, but it always says something about a network error. I have checked more than once and my network is up and running, while the website https://memorito.ir/ seems to be offline. I can reach any other website. Is this a temporary issue?
I know it's not exactly a bug, but I have no other way to contact you.

**Comment by nikgolkar** [comment]
Hello, dear Sabrina

I am very sorry for my late reply.

Unfortunately, Memorito was stopped midway through development, and the Memorito server was not economical to be online and may be offline forever. But the server-side source code is available on my GitHub, although the database needs to be built by yourself.

[Memorito-server-side-link](https://github.com/Mr17MG/Memorito-API)

**Comment by nikgolkar** [comment]
If you want see more pictures from Memorito, you can visit its LinkedIn.

[Memorito Linkedin](https://www.linkedin.com/company/memorito/)
